#!/bin/bash

# Handle arguments
force=0

i=1
while [ $i -le $# ]; do
  case "${!i}" in
      -f|--force) force=1;;
  esac
  (( i++ ))
done


# Download and unpack the AMPL Library from NetLib
if [ -d solvers -a $force -eq 0 ]; then
  echo '  You seem to already have the AMPL Library.'
  echo '  Download again Y/N? (N)'
  read again
  [ "$again" != 'y' ] && exit 0
fi

rm -rf solvers
if [ "`which rsync`" != "" ]; then
  rsync -avz netlib.org::netlib/ampl/solvers .
else
  echo 'You need rsync for this operation'
fi
